name: Deploy to Production

on:
  push:
    branches-ignore:
      - 'release'
      - 'test'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node sample
    env:
      REMOTE_HOST:  152.67.70.82
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - run: npm ci
      - name: npm build-prod && build image && push
        run: |
          npm run build-prod
