name: Production Build Image & Push to DockerHub!

on:
  push:
    branches: release
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    env:
      REMOTE_HOST: 167.86.76.193
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      # send docker-compos.yml to remote Host
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
      - name: Deploy docker-compose.yml with rsync
        run: rsync -avz docker-compose.yml ${{ secrets.DEPLOY_USER }}@$REMOTE_HOST:/home/card2brain
      - name: Execute compose pull and cocker-compose up -d to start the container
        run: ssh card2brain@$REMOTE_HOST  "docker-compose pull ; docker-compose up -d"

